services:
  # Backend API service
  - type: web
    name: lars-workout-api
    env: node
    buildCommand: cd production && npm install
    startCommand: cd production && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://www.baselinetopsport.com/workout

  # Frontend service
  - type: web
    name: lars-workout-app
    env: static
    buildCommand: >
      cd client &&
      npm install &&
      REACT_APP_DEBUG=true npm run build &&
      echo "<!DOCTYPE html><html><head><title>Lars Workout</title></head><body><div id='root'></div><script>console.log('Debug: App mounting...')</script></body></html>" > build/debug.html
    staticPublishPath: client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Content-Type
        value: text/html
      - path: /static/js/*
        name: Content-Type
        value: application/javascript
      - path: /static/css/*
        name: Content-Type
        value: text/css
      - path: /manifest.json
        name: Content-Type
        value: application/json 